export const customers = {
  title: "Customers",
  labels: [
    "Customer No",
    "Fist name",
    "Last name",
    "Street",
    "Zip code",
    "City",
    "Shipping street",
    "Shipping zip code",
    "Shipping city",
  ],
  keys: [
    "id",
    "firstname",
    "lastname",
    "street",
    "zipcode",
    "city",
    "shippingstreet",
    "shippingzipcode",
    "shippingcity",
  ],
};

export const products = {
  title: "Products",
  labels: [
    "Product No",
    "Ean",
    "Producer",
    "Details",
    "Net Purchase Price",
    "Gross Retail Price",
    "Gross Purchase Price",
    "Tax",
    "Margin",
    "Upe",
    "Stock",
    "Product group",
    "Distributor",
  ],
  keys: [
    "id",
    "ean",
    "producer",
    "details",
    "purchase_price_without_tax",
    "retail_price_without_tax",
    "retail_price_with_tax",
    "tax",
    "margin",
    "upe",
    "stock",
    "product_group",
    "distributor",
  ],
};
