export const customers = {
  title: "Customers",
  labels: [
    "Customer No",
    "Fist name",
    "Last name",
    "Street",
    "Zip code",
    "City",
    "Shipping street",
    "Shipping zip code",
    "Shipping city",
  ],
  keys: [
    "id",
    "firstname",
    "lastname",
    "street",
    "zipcode",
    "city",
    "shippingstreet",
    "shippingzipcode",
    "shippingcity",
  ],
  types: ["number", "text", "text", "text", "number", "text", "text", "number", "text"],
  required: ["firstname", "lastname", "street", "zipcode", "city"],
};

export const products = {
  title: "Products",
  labels: [
    "Product No",
    "Ean",
    "Producer",
    "Details",
    "NPP",
    "NRP",
    "GRP",
    "Margin",
    "Tax",
    "Upe",
    "Stock",
    "Product group",
    "Distributor",
  ],
  keys: [
    "id",
    "ean",
    "producer",
    "details",
    "net_purchase_price",
    "net_retail_price",
    "gross_retail_price",
    "margin",
    "tax",

    "upe",
    "stock",
    "product_group",
    "distributor",
  ],
  types: [
    "number",
    "text",
    "text",
    "number",
    "number",
    "number",
    "number",
    "number",
    "number",
    "number",
    "text",
    "text",
  ],
  required: [
    "id",
    "ean",
    "producer",
    "details",
    "purchase_price_without_tax",
    "retail_price_without_tax",
    "retail_price_with_tax",
    "tax",
    "margin",
    "upe",
    "stock",
    "product_group",
    "distributor",
  ],
};
